version: "3.8"
services:

    # PHP Service
    php:
        build:
            context: .
            target: php
            args: 
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app
            - DB_HOST=host.docker.internal
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 8000:8000
        depends_on:
            - database

  # Node.js Service
    node:
        image: node:20
        working_dir: /var/www/react
        volumes:
        - ./:/var/www
        ports:
            - 3000:3000
        command: bash -c "cd /var/www/react && npm install && npm run dev -- --host"
        depends_on:
            - php

    # Database Server
    database:
        image: mysql:8.0
        ports:
            -   3307:3307
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            # - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        volumes:
            - db-data:/var/lib/mysql

volumes:
  db-data: ~