version: 2.1
orbs:
  node: circleci/node@5
  php: circleci/php@1

jobs:
  build-node:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: npm install --legacy-peer-deps
      - run:
          command: npm run build
      - run:
          name: Create the ~/artifacts directory if it doesn't exist
          command: mkdir -p ~/artifacts
      - run:
          name: Copy artifacts
          command: cp -R build dist public .output .next .docusaurus ~/artifacts 2>/dev/null || true
      - store_artifacts:
          path: ~/artifacts
          destination: node-build

  test-php:
    docker:
      - image: cimg/php:8.2-node
      - image: circleci/mysql:5.7   # Add MySQL service
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel  # Set the name of your test database
    steps:
      - checkout
      - run:
          name: Install composer dependencies
          command: composer install --no-interaction --prefer-dist --no-scripts --no-progress --no-suggest
      - run:
          name: Set up Laravel environment
          command: |
            cp .env.example .env
            php artisan key:generate
            # Update .env with database connection details
            sed -i 's/DB_HOST=127.0.0.1/DB_HOST=127.0.0.1/' .env
            sed -i 's/DB_DATABASE=laravel/DB_DATABASE=laravel/' .env
            sed -i 's/DB_USERNAME=root/DB_USERNAME=root/' .env
            sed -i 's/DB_PASSWORD=/DB_PASSWORD=root/' .env
      - run:
          name: Migrate the database
          command: php artisan migrate
      - run:
          name: Run PHP tests
          command: ./vendor/bin/phpunit

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - add_ssh_keys:
          fingerprints:
            - $SSH_FINGERPRINT
      - run:
          name: Deploy to AWS EC2 Instance
          command: |
            ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $EC2_USERNAME@$EC2_IP "
              cd /var/www/vhosts/laravel-react-menu/
              git pull origin main
              composer install --no-interaction --prefer-dist --optimize-autoloader
              sudo php artisan migrate --force
              sudo php artisan cache:clear
              sudo php artisan config:cache
              cd /var/www/vhosts/laravel-react-menu/react
              sudo npm install
              sudo npm run build
              sudo rm -rf node_modules
              sudo systemctl restart php-fpm
              sudo systemctl restart nginx
            "

workflows:
  build-and-test:
    jobs:
      - build-node
      - test-php:
          requires:
            - build-node
      - deploy:
          requires:
            - test-php
          filters:
            branches:
              only: main
