version: 2.1
orbs:
  cypress: cypress-io/cypress@1

executors:
  with-chrome:
    resource_class: small
    docker:
      - image: "cypress/browsers:node14.16.0-chrome90-ff88"

jobs:
  cypress-install:
    docker:
      - image: cimg/node:14.17.0
    steps:
      - checkout
      - run:
          name: Install Node.js dependencies
          command: cd react && npm install

  cypress-start:
    executor: with-chrome
    steps:
      - checkout
      - run:
          name: Start React server
          command: |
            cd react && npm install
            npm run dev & # Start server in the background
            # Wait for the server to be up and running
            for i in `seq 1 30`; do
              curl -sSf http://localhost:3000 && echo "Server is up" && exit 0
              echo -n .
              sleep 1
            done
            echo "Failed to start server" && exit 1

  cypress-run:
    executor: with-chrome
    steps:
      - checkout
      - run:
          name: Run Cypress tests
          command: cd react && npx cypress run
      - store_test_results:
          path: react/cypress/results
      - store_artifacts:
          path: react/cypress/screenshots

workflows:
  test:
    jobs:
      - cypress-install
      - cypress-start:
          requires:
            - cypress-install
      - cypress-run:
          requires:
            - cypress-start
