version: 2.1
orbs:
  node: circleci/node@5
  php: circleci/php@1

jobs:
  test-php:
    docker:
      - image: circleci/php:8.2-cli
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel
    steps:
      - checkout
      - run:
          name: Install MySQL Client
          command: |
            sudo apt-get update && sudo apt-get install -y mysql-client
      - run:
          name: Install composer dependencies
          command: composer install --no-interaction --prefer-dist --no-scripts --no-progress --no-suggest
      - run:
          name: Set up Laravel environment
          command: |
            cp .env.example .env
            php artisan key:generate
            sed -i 's/DB_HOST=127.0.0.1/DB_HOST=127.0.0.1/' .env
            sed -i 's/DB_DATABASE=laravel/DB_DATABASE=laravel/' .env
            sed -i 's/DB_USERNAME=root/DB_USERNAME=root/' .env
            sed -i 's/DB_PASSWORD=/DB_PASSWORD=root/' .env
      - run:
          name: Wait for MySQL to be ready
          command: |
            for i in {1..30}; do
              if mysql -h127.0.0.1 -uroot -proot -e 'SELECT 1'; then
                exit 0
              fi
              sleep 1
            done
            exit 1
      - run:
          name: Migrate the database
          command: php artisan migrate
      - run:
          name: Run PHP tests
          command: ./vendor/bin/phpunit

workflows:
  build-and-test:
    jobs:
      - build-node
      - test-php:
          requires:
            - build-node
      - deploy:
          requires:
            - test-php
          filters:
            branches:
              only: main
